spring.application.name=appoimentService

# DB - supports Docker env variable override
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/appoinment_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:test}

# JPA properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# Logging Configuration
# ===============================
logging.level.root=INFO
logging.level.com.barberService.appoimentservice=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# ------------------------------
# Resilience4j Config for Slot Service
# ------------------------------
resilience4j.retry.instances.slotService.max-attempts=3
resilience4j.retry.instances.slotService.wait-duration=1s
resilience4j.timeLimiter.instances.slotService.timeout-duration=2s

server.port=8088
slot.service.url=${SLOT_SERVICE_URL:http://localhost:8089}

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}