logging:
  level:
    org.springframework.cloud.gateway: DEBUG

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"

            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "PATCH"
              - "DELETE"
              - "OPTIONS"

            allowedHeaders:
              - "*"

            allowCredentials: true
            maxAge: 3600