server:
  port: 9090




spring:
  application:
    name: barberShopGateway

  cloud:
    gateway:
                 # browser caches preflight for 1 hour
      routes:
        - id: shop-service
          uri: ${SHOP_SERVICE_URL:http://localhost:8089}
          predicates:
            - Path=/api/shop/**
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8087}
          predicates:
            - Path=/api/v1/auth/**,/api/v1/users/**


      # IMPORTANT: This prevents the gateway from passing its own CORS headers
      # to downstream services and getting duplicate headers in the response
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin