name: barber booking service CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

       #Discovery servr
      - name: Build Discovery Server
        run: |
         cd discovery-server
         mvn clean install -DskipTests 
         docker build -t discovery-server
         

      #API Gateway
      - name: Build API Gateway
        run: |
         cd apiGateWay
         mvn clean install -DskipTests
         docker build -t api-gateWay

      #Barber service    
      - name: Build Barber service  
        run: |
          cd barberService
          mvn clean install -DskipTests
          docker build -t barber-service .
        
